site_name: tengasell
site_description: API to leverage the tengasell platforms mobile app and web app as well.
repo_url: https://github.com/Rmaravanyika/tengasell_api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Rmaravanyika">Rmaravanyika</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
